export const GET_USER = 'GET_USER';
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING_ERROR = 'USER_LOADING_ERROR';
export const CHANGE_COMPARISON_GROUP = 'CHANGE_COMPARISON_GROUP';
